### ISSUE TITLE
strange translations show up in database

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#213] opened 2016-01-09 23:56 UTC
new petitions show up with (several) translations in the database, with strange values for locale (like nl?locale=nl) while the original petition the translations refer to is often empty

the translations are not translations, but several versions of the original text

in the new petitions grid there is an overview of petitions which are empty in the translated version, while the orginal version then should appear

The titles of those petitions also do not match the title of the orginal, moderated (and improved) title. The translations have the unmoderated title. If any, because some have no title at all. 

The url of the petitions linked from this view is not the slug, but the petition_id or the unmoderated title. 
![screen shot 2016-01-10 at 00 56 04](https://cloud.githubusercontent.com/assets/98476/12219102/f727bd0a-b734-11e5-90e5-eae52d614bc0.png)

**Comment by spreeker** [comment] 2016-01-10 09:04
https://petities.nl/petitions?locale=en&sorting=newest, reloading this page sometimes like 1 in 4 gives me the correct page... I have no clue @johankok do you have an idea? I think the issue only occurs with 0 signatures.

I can not reproduce this error on my development environment.
looks like an concurrency issue.

**Comment by spreeker** [comment] 2016-01-10 09:16
We should make an explicit dropbox in the petition edit page so you can save other translations.

**Comment by spreeker** [comment] 2016-01-10 11:19
c2b11883ea76ad878d5b4b3268414e964a10a81c did some attempt at improving i18n fallback

**Comment by spreeker** [comment] 2016-01-10 11:23
Seems to be fixed now on production.

**Closed as completed by spreeker** 2016-01-10 11:23 UTC
Labels: bug
