### ISSUE TITLE
signing with escape charachter impossible

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#393] opened 2016-04-12 08:53 UTC
signatory signed with a / instead of a . in her name. The signatory did not go to the database, but she did receive a confirmation e-mail. 

Perhaps the input form should be protected from escape characters? 

https://opendomein.nl/cerb5/display/TLL-23932-969

**Comment by skoolstra** [comment] 2017-05-23 19:02
I am unable to reproduce this issue. This issue was created over a year ago and much has changed to confirmation code since that point. I am closing this issue, please feel free to reopen if you believe the issue still exists today.

**Closed as completed by skoolstra** 2017-05-23 19:02 UTC
Labels: bug
