### ISSUE TITLE
Creating new user fails when user supplies a short password

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#314] opened 2016-02-19 16:02 UTC
Without password a user can create a petition, when a user choses a too short password  the confirmation e-mail never arrives and the new user is not created.

https://opendomein.nl/cerb5/display/EJF-63381-943

This occurs often, this user https://opendomein.nl/cerb5/display/MRE-62921-264 is the latest.

One user reports that the password she chose consisted of numbers only, so strange characters cannot be the problem https://opendomein.nl/cerb5/display/RSI-74427-915

Reconstruction of the error is possible with a 6 digit password, a 7 digit password, and with an 8 digit password the error does NOT occur!

**Comment by skoolstra** [comment] 2017-06-17 07:12
This issue is a duplicate of #253.

**Closed as completed by skoolstra** 2017-06-17 07:12 UTC
Labels: bug
