### ISSUE TITLE
improve orphaned route

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#264] opened 2016-01-25 09:17 UTC
only the signatories who were sent an invite to adopt should be able to /becomeowner of a petition, not just anyone. Sending out invitations to adopt should halt as soon as any one followed the /becomeowner link to adopt. Previously sent invitees can still adopt and simply become owner together with others who were faster to respond. 

Also, if the first owner changes the hand over date, the invitations to adopt mailing should halt. The petitioner might find some co-owners active all of a sudden, but that is of later concern. In the e-mail warning to get active this should be explained.

**Comment by johankok** [comment] 2019-10-05 17:51
The `/becomeowner` route was removed years ago because it didn't function as expected. Closing this issue as a duplicate of #400.

**Closed as completed by johankok** 2019-10-05 17:51 UTC
Labels: bug
