### ISSUE TITLE
status petition missing translations

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#188] opened 2016-01-02 20:35 UTC
missing description for:live shows on edit petition view
probably also for other statuses

**Comment by skoolstra** [comment] 2016-12-16 08:17
This issue was created almost one year ago and I am unable to reproduce the error. Please feel free to reopen this bug if the problem still occurs.

**Comment by rrustema** [comment] 2016-12-21 10:07
![screen shot 2016-12-21 at 11 03 59](https://cloud.githubusercontent.com/assets/98476/21385108/8da1c9da-c76d-11e6-8f79-6f8867a71b8d.png)

A text there should give instructions to the user for that particular status. In the case of 'live', for example "While the petition is open you can campaign for signatures and prepare the hand over. Consult the 'handbook' about this." (Terwijl de petitie open is kan je ondertekenaars werven en de overhandiging voorbereiden. Zie het 'handboek' hierover."

**Comment by skoolstra** [comment] 2017-02-26 09:00
This was resolved in 5fdd88d.

**Closed as completed by skoolstra** 2017-02-26 09:00 UTC
Labels: bug
