### ISSUE TITLE
sort order petitions in petition desk

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#260] opened 2016-01-21 21:20 UTC
latest first, oldest later. Now the other way round, not useful says https://opendomein.nl/cerb5/display/AIL-77411-886

**Comment by skoolstra** [comment] 2016-04-13 19:19
Closing this issue, as I think this is a duplicate of #382. Please feel free to reopen if you do not agree.

**Closed as completed by skoolstra** 2016-04-13 19:19 UTC
Labels: bug
