### ISSUE TITLE
petitioner can not change description

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#356] opened 2016-03-10 10:28 UTC
https://opendomein.nl/cerb5/display/BXF-95212-541 got into trouble because of an incorrect self description (a petition about the safety of a road on behalf of the school, rather then the pupils of a school). 

Currently a petitioner should be able to change the self description and e-mail address as displayed on the petition, but the information in the profile (only visible to the petition desk) should not be fixed. After all, the e-mail address is the username. In the profile the address is in an input field which gives the illusion that it can be changed. But it in fact it can not change. The address should not be in a form field, but displayed as fixed information. 

The descriptive information is suggesting the address can be changed, while it can only be changed by the admin. This should be adapted. 

The personal information in the details of a petition on display now are the values of the user details, not the one from the petition. These can be changed by the petitioner, but are only shown in the edit view. 

See illustrations, 
1. profile page in edit view
2. profile page in show view
3. petition details box in edit view
4. petitions details box in show view after saving edit in 3
by the way, the edit in 3 reappears (is saved somewhere) after going back to edit view after show view 4.

![screen shot 2016-03-10 at 11 27 40](https://cloud.githubusercontent.com/assets/98476/13666694/2920a03a-e6b3-11e5-8d26-059424cb4ef4.png)
![screen shot 2016-03-10 at 11 27 29](https://cloud.githubusercontent.com/assets/98476/13666696/2c8fdf10-e6b3-11e5-972f-f75c50626fa8.png)
![screen shot 2016-03-10 at 11 27 08](https://cloud.githubusercontent.com/assets/98476/13666698/2fe653ec-e6b3-11e5-84ca-97eab6556e66.png)
![screen shot 2016-03-10 at 11 26 48](https://cloud.githubusercontent.com/assets/98476/13666700/32fc0004-e6b3-11e5-800e-d4945cbe0aff.png)

**Comment by skoolstra** [comment] 2018-03-20 20:42
This issue was resolved a couple of months ago. I am closing this issue, please feel free to reopen if you believe the issue still exists today.

**Comment by rrustema** [comment] 2018-03-20 21:41
Yes, the public part is now correct. But there is one possibly confusing detail. In the 'edit profile' view of 'my profile' the e-mailaddress (which is the username) appears in the form. While this cannot be changed because this address is confirmed/validated. If someone tries to change it it is not accepted, but probably people are trying this endlessly under the assumption that this is the place to change how an e-mailaddress appears to signatories.

**Comment by skoolstra** [comment] 2019-10-05 17:37
> Yes, the public part is now correct. But there is one possibly confusing detail. In the 'edit profile' view of 'my profile' the e-mailaddress (which is the username) appears in the form. While this cannot be changed because this address is confirmed/validated. If someone tries to change it it is not accepted, but probably people are trying this endlessly under the assumption that this is the place to change how an e-mailaddress appears to signatories.

And this is a duplicate of #387.

**Closed as completed by skoolstra** 2019-10-05 17:37 UTC
Labels: bug
