### ISSUE TITLE
e-mail to petitioner misses name and username 

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#307] opened 2016-02-17 15:17 UTC
After creating a petition the petitioner receives an e-mail with "Verder met uw petitie" in the subject. 

Missing in those e-mails are the name and username. 

For example https://opendomein.nl/cerb5/display/ESD-93732-563

**Comment by skoolstra** [comment] 2017-09-30 07:19
This issue is a duplicate of #429 and was resolved in 14eb288b4abe3d93e7088cf5b54fe85059b642e3.

**Closed as completed by skoolstra** 2017-09-30 07:19 UTC
Labels: bug
