### ISSUE TITLE
graph of signature development for closed petitions

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#388] opened 2016-04-11 06:28 UTC
There are many closed petitions in the archive without a graphic for the statistics of signature development nor without an image.

https://petities.nl/petitions/all?locale=nl&sorting=concluded

While it is especially interesting to see those graphs in the grid view to get a perspective on how these developments went with petitions in the past. 

Currently, just an empty green square is displayed in grid view or in the details section. 

When a petition closes the history of the entire petition should be calculated and shown in the graph to be stored for posterity. And it should be calculated once for all closed petitions without such a graphic.

**Comment by skoolstra** [comment] 2018-08-26 19:27
Duplicate of #303

**Closed as completed by skoolstra** 2018-08-26 19:27 UTC
Labels: enhancement
